# prometheus.yml
global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "prometheus-job"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app-metrics"
    scrape_interval: 60s # every 1 minute
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:3000"]
# incase you're planning to publish to AWS Managed Prometheus `remote write` endpoint
# # ***********************************************************************************
# remote_write:
#   - url: "${PROMETHEUS_WORKSPACE_ENDPOINT}api/v1/remote_write"
#     sigv4:
#       region: "us-east-1"
# # remote_write url will look like: https://aps-workspaces.my-region.amazonaws.com/workspaces/my-workspace-id/api/v1/remote_write
