{
 "title": "API Metrics",
 "description": "Metrics of APIs in the express app",
 "tags": [
  "node.js",
  "express",
  "prometheus",
  "api"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request Count By Paths",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_requests_total{}) by (route, method)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Total Request Count by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{}[$interval])) by (status,le))",
     "legendFormat": "{{status}} (95%)"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket{}[$interval])) by (status,le))",
     "legendFormat": "{{status}} (100%)"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{}[$interval])) by (route, method)",
     "legendFormat": "{{status}} {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(http_response_length_bytes_sum{}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}