apiVersion: 1

# refer commented configs incase you use 'AWS Managed Prometheus Workspace' as datasource
datasources:
  - name: DS_PROMETHEUS
    uid: prometheus-datasource # this name and uuid must match the same as in dashboard json
    type: prometheus
    access: proxy
    # url: "https://aps-workspaces.${PROMETHEUS_REGION}.amazonaws.com/workspaces/${PROMETHEUS_WORKSPACE_ID}"
    url: "http://localhost:9090"
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: "POST"
      # oauthPassThru: false
      # sigV4Auth: true
      # sigV4AuthType: "default"
      # sigV4Region: "us-east-1"
      timeInterval: "60s"
